---
- name: Populate package facts so we can detect if other firewalls are present.
  package_facts:
    manager: auto

- name: Populate service facts so we can detect if other firewalls are running.
  service_facts:

- name: Ensure that variables are correctly set.
  include_tasks: variable_check.yml

- name: Ensure the ufw service is stopped and disabled.
  service:
    name: ufw
    state: stopped
    enabled: false
  when:
    - "'ufw' in ansible_facts.packages"
    - "'ufw' in ansible_facts.services"

- name: Ensure the ufw package is uninstalled.
  package:
    name: ufw
    state: absent
  when: "'ufw' in ansible_facts.packages"

- name: Ensure the iptables services is stopped and disabled.
  service:
    name: iptables
    state: stopped
    enabled: false
  when:
    - "'iptables' in ansible_facts.packages"
    - "'iptables' in ansible_facts.services"

- name: Ensure required packages are installed.
  package:
    name: "{{ firewalld_packages }}"
    state: present
  when: ansible_distribution != "Debian"

- name: Use nftables instead of iptables as the backend on Ubuntu.
  lineinfile:
    dest: /etc/firewalld/firewalld.conf
    regexp: "^FirewallBackend=iptables"
    line: "FirewallBackend=nftables"
    state: present
    backup: true
    mode: "0644"
  when: ansible_distribution == "Ubuntu"

- name: Make sure to allow the custom SSH port, if one is defined, before anything else.
  firewalld:
    port: "{{ firewalld_ssh_port }}/tcp"
    zone: public
    permanent: true
    state: enabled
    offline: true
  when: firewalld_ssh_port | length > 0

# - name: Ensure the firewalld service is started and enabled at boot.
#   service:
#     name: firewalld
#     state: "{{ firewalld_state | default('started') }}"
#     enabled: "{{ firewalld_enabled_at_boot | default('false') }}"

- name: Include tasks about zone management.
  include_tasks: zone_management.yml

- name: Include tasks about port and service management.
  include_tasks: service_port_management.yml

- name: Include tasks about rich rules.
  include_tasks: rich_rules.yml
