---
- name: Add/remove rich rule.
  firewalld:
    zone: "{{ item.0.zone | default('public') }}"
    rich_rule: "{{ item.1 | default('') }}"
    state: "{{ item.0.state }}"
    offline: true
    permanent: true
  when:
    - firewalld_rich_rules | length > 0
  loop: "{{ firewalld_rich_rules | subelements('rule') }}"
