---
- name: Register all firewalld's zones.
  command: "firewall-offline-cmd --get-zones"
  register: _firewalld_zone_list
  changed_when: false

- name: Register firewalld's default zone.
  command: "firewall-offline-cmd --get-default-zone"
  register: _firewalld_default_zone
  changed_when: false

- name: Create new zone(s).
  command: "firewall-offline-cmd --new-zone={{ item }}"
  when: not item in _firewalld_zone_list.stdout
  loop: "{{ firewalld_add_new_zone | flatten(levels=1) }}"

# - name: Force handlers to run immediately.
#   meta: flush_handlers

- name: Set firewalld default zone.
  command: "firewall-offline-cmd --set-default-zone={{ firewalld_default_zone | default('public') }}"
  register: _firewalld_zone_change_result
  changed_when: _firewalld_zone_change_result != "success"
  when: _firewalld_default_zone.stdout != firewalld_default_zone

- name: Enable/disable masquarading in a zone.
  firewalld:
    zone: "{{ item.zone }}"
    masquerade: "{{ item.masquerade | default('true') }}"
    state: "{{ item.state }}"
    permanent: "{{ item.permanent | default('true') }}"
    # immediate: "{{ item.immediate | default('false') }}"
    offline: true
  loop: "{{ firewalld_zone_masquerading | flatten(levels=1) }}"
  loop_control:
    label: "Masquerading {{ 'enabled' if item.state == 'enabled' else 'disabled' }} for zone {{ item.zone }}"

- name: Change the default target of a zone.
  firewalld:
    zone: "{{ item.zone }}"
    state: "{{ item.state }}"
    target: "{{ item.target }}"
    permanent: "{{ item.permanent | default('true') }}"
    offline: true
  loop: "{{ firewalld_zone_target | flatten(levels=1) }}"

- name: Register assigned zone interfaces.
  command: "firewall-offline-cmd --list-interfaces --zone={{ item.0.zone }}"
  register: _firewalld_zone_interfaces
  changed_when: false
  when:
    - firewalld_zone_interfaces | length > 0
  loop: "{{ firewalld_zone_interfaces | subelements('interface') }}"

- name: Add/remove interfaces to/from a zone.
  command: "firewall-offline-cmd {{ '--add-interface' if item.0.state == 'enabled' else '--remove-interface' }}={{ item.1 }} --zone={{ item.0.zone }}"
  when: 
    - firewalld_zone_interfaces | length > 0
    - not item.1 in _firewalld_zone_interfaces | json_query('results[*].stdout')
  loop: "{{ firewalld_zone_interfaces | subelements('interface') }}"

- name: Register assigned zone sources.
  command: "firewall-offline-cmd --list-sources --zone={{ item.0.zone }}"
  register: _firewalld_zone_sources
  changed_when: false
  when:
    - firewalld_zone_sources | length > 0
  loop: "{{ firewalld_zone_sources | subelements('source') }}"

- name: Add/remove sources to/from a zone.
  command: "firewall-offline-cmd {{ '--add-source' if item.0.state == 'enabled' else '--remove-source' }}={{ item.1 }} --zone={{ item.0.zone }}"
  when: 
    - firewalld_zone_sources | length > 0
    - not item.1 in _firewalld_zone_sources | json_query('results[*].stdout')
  loop: "{{ firewalld_zone_sources | subelements('source') }}"