---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update apt cache.
      apt:
        upgrade: true
        update_cache: true
      when: ansible_distribution == "Ubuntu"

    - name: Update pacman cache.
      pacman:
        update_cache: yes
        upgrade: yes
      when: ansible_os_family == "Archlinux"

  tasks:

    - name: read vars from first file found, use 'vars/' relative subdir
      include_vars: "{{ lookup('first_found', params) }}"
      vars:
        params:
          files:
            - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
            - vars.yml
          paths:
            - './vars'

    - name: "Include ansible-role-firewalld"
      include_role:
        name: "ansible-role-firewalld"
